### ISSUE TITLE
Failed to access the ISMIR2014 dataset

### ISSUE THREAD

**Issue by SylviaZiyaZhou** [itec-hust/MusicYOLO#1]
Hi! I found the link provided in the paper didn't work for downloading the dataset. Could you please share the available link here? Thanks a lot!

**Comment by xk-wang** [comment]
The ISMIR2014 dataset is too small and too old. We downloaded it a long time ago on our machine. There is no link. It is recommended to use MIR-ST500 dataset or SSVD dataset, which are mentioned in our latest paper https://ieeexplore.ieee.org/document/9944977.
